# Generated by Django 4.0.3 on 2022-12-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_alter_hat_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationvo',
            old_name='href',
            new_name='import_href',
        ),
    ]
