# Generated by Django 4.0.3 on 2022-12-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_binvo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
